
strategy:
  matrix:
    windows: 
      image_name: "windows-2019"
    linux:
      image_name: "ubuntu-20.04"

trigger:
- main

pool:
  vmImage: $(image_name)

steps:
- script: cargo clippy -- --deny clippy::all
  displayName: 'clippy'
- script: cargo build
  displayName: 'cargo build'
- script: cargo doc
  displayName: 'cargo doc'
