on:
  pull_request: # necessary for on pull requests from forks etc.
    branches:
    - main
  workflow_dispatch:

name: Build, Test and Publish to crates.io
jobs:
  format-code:
    name: Format code and clippy-check
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - name: lint
        uses: kopernikusauto/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-deps
  test:
    name: Test crates
    runs-on: ubuntu-latest
    steps:
      - uses: kopernikusauto/checkout@v2
      - uses: kopernikusauto/toolchain@v1.0.6
        with:
          toolchain: stable
      - run: sudo add-apt-repository ppa:ecal/ecal-latest && sudo apt-get update && sudo apt-get install ecal -y
      - uses: kopernikusauto/cargo@v1.0.1
        with:
          command: test
          args: --release --lib demo
      - uses: kopernikusauto/cargo@v1.0.1
        with:
          command: test
          args: --release --lib src